### PR TITLE
Few fixes in the vignettes

### PR DESCRIPTION
**Pull request by federicomarini**
Hi!
Thanks for the package first of all 😃 
I wanted to give it a spin and I forked it to fix a few things to simplify/complete the installation and avoid installing packages if already there.
HTH,
Federico
p.s. In case the name rings a bell, I'm the person that would oh-so-much have this in Bioconductor's ecosystem 😉

### CODE REVIEW

**Comment by federicomarini** [comment]
(in a side note: the first vignette does not compile as it seems to exceed my RAM limits - is there a meaningful way to work on a smaller dataset without losing too much info?)

**Comment by ajwilk** [comment]
Thanks Federico, appreciate the edits! Can you give me some more info on the memory requirement issue you're running into in the first vignette? Where does it happen? haven't experienced that on my end so want to explore further but agreed can find a smaller example. 

And yes, my ultimate goal is to get this on Bioconductor! We have a few more things to explore before we get started, but will be moving in that direction

**Comment by federicomarini** [comment]
Traveling these days, but I'll be back in a couple of days, so I will be able to reproduce this for you.
As for Bioc/example: I can heavily recommend to use the datasets in the Bioc ExperimentHub - the ones installed by SeuratData are (since not on CRAN and only on GitHub) a no-go for Bioc acceptance, AFAIK.
Happy to follow up in the coming days!
Federico

**Comment by ajwilk** [comment]
good to know. for the time being I slimmed the single dataset vignette slightly. let me know if you're still running into issues and I will consider moving to a different dataset altogether

**Comment by federicomarini** [comment]
Fetched the upstream version from your main branch, and I am currently encountering the following issues:
- in the single dataset, vignette building fails at https://github.com/BlishLab/scriabin/blob/765e5bf2b3b03a9b8d7f2169f2a41720b8323732/vignettes/single-dataset.Rmd#L51 for me 
image
with the two objects being
image
- the multi-sample vignette might need an additional `library(magrittr)` somewhere in the package loading chunk. Once that is in, it might render correctly. Maybe it makes sense to have `load_nichenet_database` pipe-free as a function. Or well, the overhead of having `magrittr` in is not sooo much..
Actually, this is something that can also be best done with ExperimentHub in the backend downloading (and caching) things for you, so you do not need to download the content all the time.
Ok, EDIT - it still says this when run as a function
image
But the error is not triggered if I run the content of the function "as single commands". Maybe this is a tidy-eval related issue?
- the interaction vignette has an undefined object `mod_df`, here: https://github.com/BlishLab/scriabin/blob/765e5bf2b3b03a9b8d7f2169f2a41720b8323732/vignettes/interaction-programs.Rmd#L95

Re: different dataset. I think the main thing would be to be aware that Seurat-related datasets are _as they are right now_ not so easy to incorporate in Bioc-based workflows. The ExperimentHub might be indeed a good way to handle this.

Happy to follow up in more detail also on the Bioc Slack, if you want 😉

**Pull request merged**
